@extends('layouts.marketing')
@section('title', 'About | AgriShield AI')
@section('description', 'Learn why AgriShield is building accountable crop-support operations for field teams and farmers across Northern Nigeria.')
@section('content')
<section class="inner-hero"><p class="eyebrow light"><span></span> About AgriShield</p><h1>Crop support needs<br>operational memory.</h1><p>We are building practical software for crop programmes and the field teams responsible for farmer follow-through across Northern Nigeria.</p></section>
<section class="editorial-split section-pad"><div><p class="eyebrow"><span></span> Why this product</p><h2>Important field context should not disappear between messages.</h2></div><div><p>Farm records, crop seasons, farmer questions and advisories often sit in different tools—or in no system at all.</p><p>AgriShield brings those records into one authorised workflow so a team can see what was reported, what was reviewed and what happened next.</p></div></section>
<section class="principles section-pad"><div class="section-heading"><p class="eyebrow"><span></span> Product discipline</p><h2>Focused enough<br><em>to be useful.</em></h2></div><div class="trust-grid"><article><span>01</span><h3>Crop support focus</h3><p>The current product stays centred on crop records, questions, cases and follow-through.</p></article><article><span>02</span><h3>Private records</h3><p>Farm, voice and image records stay inside authorised organisation workflows.</p></article><article><span>03</span><h3>Visible limits</h3><p>Provider-dependent automation is labelled instead of being presented as available by default.</p></article><article><span>04</span><h3>Accountable action</h3><p>Cases, advisories and acknowledgements retain a useful operational trail.</p></article></div></section>
<section class="capability-team section-pad"><div><p class="eyebrow light"><span></span> The work behind AgriShield</p><h2>A multidisciplinary product requires clear ownership.</h2></div><div><article><strong>Crop operations</strong><p>Shape workflows around real extension and programme decisions.</p></article><article><strong>Product engineering</strong><p>Build secure web and API surfaces that field teams can operate.</p></article><article><strong>Deployment support</strong><p>Configure organisations, roles and crop workflows for a focused rollout.</p></article></div></section>
@include('website.partials.cta')
@endsection
