@extends('layouts.marketing')
@section('title', 'About | AgriShield AI Ltd')
@section('content')
<section class="inner-hero"><p class="eyebrow light"><span></span> About us</p><h1>Technology grounded<br>in local reality.</h1><p>We are building the trusted digital infrastructure North-East Nigeria’s agricultural future deserves.</p><div class="inner-hero-meta"><strong>6</strong><span>states connected by one agricultural vision</span></div></section>
<section class="editorial-split section-pad"><div><p class="eyebrow"><span></span> Our point of view</p><h2>The best intelligence begins with listening.</h2></div><div><p>AgriShield AI is an agricultural intelligence and digital transformation company working at the intersection of field knowledge, responsible AI, geospatial science and public programme delivery.</p><p>We design around the institutions that coordinate agriculture and the communities who depend on those decisions.</p></div></section>
<section class="principles section-pad"><div class="section-heading"><p class="eyebrow"><span></span> How we work</p><h2>Principles that travel<br><em>from strategy to field.</em></h2></div><div class="trust-grid"><article><span>01</span><h3>Listen before building</h3><p>Begin with people, institutions and the decisions the system must improve.</p></article><article><span>02</span><h3>Design for the last mile</h3><p>Make offline resilience, clear interfaces and practical support foundational.</p></article><article><span>03</span><h3>Make trust visible</h3><p>Build privacy, validation, auditability and responsible AI into every workflow.</p></article><article><span>04</span><h3>Measure what matters</h3><p>Connect platform outputs to programme outcomes and community impact.</p></article></div></section>
<section class="mini-team section-pad"><div><p class="eyebrow light"><span></span> Leadership</p><h2>People with a bias for useful change.</h2><a class="button button-orange" href="{{ route('team') }}">Meet the team <span>→</span></a></div><div class="leader-list"><article><span>DA</span><div><small>Chief Executive Officer</small><strong>Dr. Amina Bello</strong><p>Agricultural systems strategist focused on inclusive digital transformation and regional food security.</p></div></article><article><span>EM</span><div><small>Director, Data & AI</small><strong>Engr. Musa Ibrahim</strong><p>Data architect building responsible intelligence platforms for public programmes and field operations.</p></div></article><article><span>HA</span><div><small>Head of Programmes</small><strong>Hauwa Abubakar</strong><p>Programme leader connecting government priorities, development partners and farming communities.</p></div></article></div></section>
@include('website.partials.cta')
@endsection
