@extends('layouts.marketing')
@section('title', __('marketing.pages.contact.meta_title'))
@section('description', __('marketing.pages.contact.meta_description'))
@section('content')
<div class="gs-inner">
    <section class="gs-contact-intro gs-container"><div><p class="gs-context">{{ __('marketing.pages.contact.eyebrow') }}</p><h1>{{ __('marketing.pages.contact.title') }}</h1><p>{{ __('marketing.pages.contact.intro') }}</p><dl><div><dt>{{ __('marketing.pages.contact.email') }}</dt><dd><a href="mailto:hello@agrishield.ai">hello@agrishield.ai</a></dd></div><div><dt>{{ __('marketing.pages.contact.region') }}</dt><dd>{{ __('marketing.pages.contact.region_value') }}</dd></div></dl></div>
        <form class="gs-contact-form" action="mailto:hello@agrishield.ai" method="GET"><header><h2>{{ __('marketing.pages.contact.form_title') }}</h2><p>{{ __('marketing.pages.contact.form_body') }}</p></header><div class="gs-form-grid"><div><label for="contact-name">{{ __('marketing.pages.contact.name') }}</label><input id="contact-name" name="subject" required placeholder="{{ __('marketing.pages.contact.name_placeholder') }}"></div><div><label for="contact-email">{{ __('marketing.pages.contact.work_email') }}</label><input id="contact-email" name="email" type="email" autocomplete="email" required placeholder="name@organization.org"></div><div class="wide"><label for="contact-organisation">{{ __('marketing.pages.contact.organisation') }}</label><input id="contact-organisation" name="organisation" autocomplete="organization" placeholder="{{ __('marketing.pages.contact.organisation_placeholder') }}"></div><div class="wide"><label for="contact-interest">{{ __('marketing.pages.contact.interest') }}</label><select id="contact-interest" name="interest">@foreach(__('marketing.pages.contact.options') as $option)<option>{{ $option }}</option>@endforeach</select></div><div class="wide"><label for="contact-message">{{ __('marketing.pages.contact.message') }}</label><textarea id="contact-message" name="body" rows="5" placeholder="{{ __('marketing.pages.contact.message_placeholder') }}"></textarea></div><button class="gs-button gs-button-primary wide" type="submit">{{ __('marketing.pages.contact.submit') }} ↗</button><small class="wide">{{ __('marketing.pages.contact.privacy') }}</small></div></form>
    </section>
</div>
@endsection
