@extends('layouts.marketing')
@section('title', __('marketing.pages.contact.meta_title'))
@section('description', __('marketing.pages.contact.meta_description'))
@section('content')
<div class="inner-site">
    <section class="inner-page-hero inner-page-hero-text inner-page-hero-contact"><div data-motion="hero-copy"><p class="agri-kicker agri-kicker-light"><span></span>{{ __('marketing.pages.contact.eyebrow') }}</p><h1>{{ __('marketing.pages.contact.title') }}</h1><p>{{ __('marketing.pages.contact.intro') }}</p></div></section>
    <section class="inner-contact inner-section"><div><p class="agri-kicker"><span></span>{{ __('marketing.pages.contact.form_label') }}</p><h2>{{ __('marketing.pages.contact.form_title') }}</h2><p>{{ __('marketing.pages.contact.form_body') }}</p><dl><div><dt>{{ __('marketing.pages.contact.email') }}</dt><dd><a href="mailto:hello@agrishield.ai">hello@agrishield.ai</a></dd></div><div><dt>{{ __('marketing.pages.contact.region') }}</dt><dd>{{ __('marketing.pages.contact.region_value') }}</dd></div></dl></div><form class="inner-contact-form" action="mailto:hello@agrishield.ai" method="GET"><div><label for="contact-name">{{ __('marketing.pages.contact.name') }}</label><input id="contact-name" name="subject" required placeholder="{{ __('marketing.pages.contact.name_placeholder') }}"></div><div><label for="contact-email">{{ __('marketing.pages.contact.work_email') }}</label><input id="contact-email" type="email" required placeholder="name@organization.org"></div><div class="wide"><label for="contact-organisation">{{ __('marketing.pages.contact.organisation') }}</label><input id="contact-organisation" placeholder="{{ __('marketing.pages.contact.organisation_placeholder') }}"></div><div class="wide"><label for="contact-interest">{{ __('marketing.pages.contact.interest') }}</label><select id="contact-interest" name="interest">@foreach(__('marketing.pages.contact.options') as $option)<option>{{ $option }}</option>@endforeach</select></div><div class="wide"><label for="contact-message">{{ __('marketing.pages.contact.message') }}</label><textarea id="contact-message" name="body" rows="5" placeholder="{{ __('marketing.pages.contact.message_placeholder') }}"></textarea></div><button class="agri-button agri-button-primary wide" type="submit">{{ __('marketing.pages.contact.submit') }} <span aria-hidden="true">↗</span></button><small class="wide">{{ __('marketing.pages.contact.privacy') }}</small></form></section>
</div>
@endsection
