@extends('layouts.marketing')
@section('title', __('marketing.pages.field_voice.meta_title'))
@section('description', __('marketing.pages.field_voice.meta_description'))
@section('content')
<div class="inner-site">
    <section class="inner-page-hero inner-page-hero-voice"><div data-motion="hero-copy"><p class="agri-kicker agri-kicker-light"><span></span>{{ __('marketing.pages.field_voice.eyebrow') }}</p><h1>{{ __('marketing.pages.field_voice.title') }}</h1><p>{{ __('marketing.pages.field_voice.intro') }}</p></div><div class="inner-hero-instrument instrument-voice" data-motion="hero-media" aria-hidden="true"><span>HA / 00:18</span><div>@for($i = 0; $i < 13; $i++)<i></i>@endfor</div><b>VOICE → CONTEXT → REVIEW</b></div></section>
    <section class="inner-voice-workflow inner-section"><div><p class="agri-kicker"><span></span>{{ __('marketing.pages.field_voice.workflow_label') }}</p><h2>{{ __('marketing.pages.field_voice.workflow_title') }}</h2><ol>@foreach(__('marketing.pages.field_voice.steps') as $step)<li><span>{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div><strong>{{ $step['title'] }}</strong><p>{{ $step['body'] }}</p></div></li>@endforeach</ol></div><aside><small>{{ __('marketing.pages.field_voice.panel_badge') }}</small><div class="voice-orb"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 4a5 5 0 0 0-5 5v7a5 5 0 0 0 10 0V9a5 5 0 0 0-5-5Z"/><path d="M7 15v1a9 9 0 0 0 18 0v-1M16 25v4M11 29h10"/></svg></div><h3>{{ __('marketing.pages.field_voice.panel_title') }}</h3><p>{{ __('marketing.pages.field_voice.panel_body') }}</p>@auth @if(auth()->user()->primaryOrganizationId())<a class="agri-button agri-button-yellow" href="{{ route('organization.voice-assistance.index', auth()->user()->primaryOrganizationId()) }}">{{ __('marketing.pages.field_voice.panel_action') }}</a>@endif @else<a class="agri-button agri-button-yellow" href="{{ route('login') }}">{{ __('marketing.pages.field_voice.panel_signin') }}</a>@endauth</aside></section>
    <section class="inner-section inner-bounds"><header><p class="agri-kicker"><span></span>{{ __('marketing.pages.field_voice.bounds_label') }}</p><h2>{{ __('marketing.pages.field_voice.bounds_title') }}</h2></header><div><article><strong>{{ __('marketing.pages.field_voice.core_title') }}</strong><ul>@foreach(__('marketing.pages.field_voice.core_items') as $item)<li>{{ $item }}</li>@endforeach</ul></article><article><strong>{{ __('marketing.pages.field_voice.provider_title') }}</strong><ul>@foreach(__('marketing.pages.field_voice.provider_items') as $item)<li>{{ $item }}</li>@endforeach</ul></article></div></section>
</div>
@endsection
