@extends('layouts.marketing')
@section('title', __('marketing.pages.field_voice.meta_title'))
@section('description', __('marketing.pages.field_voice.meta_description'))
@section('content')
<div class="gs-inner">
    <section class="gs-voice-hero"><div class="gs-container"><div><p class="gs-context">{{ __('marketing.pages.field_voice.eyebrow') }}</p><h1>{{ __('marketing.pages.field_voice.title') }}</h1><p>{{ __('marketing.pages.field_voice.intro') }}</p></div><aside aria-label="Hausa voice note example"><span>HA / 00:18</span><div>@for($i = 0; $i < 13; $i++)<i></i>@endfor</div><b>VOICE → CONTEXT → REVIEW</b></aside></div></section>
    <section class="gs-voice-flow gs-container"><div><h2>{{ __('marketing.pages.field_voice.workflow_title') }}</h2><ol>@foreach(__('marketing.pages.field_voice.steps') as $step)<li><span>{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div><strong>{{ $step['title'] }}</strong><p>{{ $step['body'] }}</p></div></li>@endforeach</ol></div><aside><small>{{ __('marketing.pages.field_voice.panel_badge') }}</small><h3>{{ __('marketing.pages.field_voice.panel_title') }}</h3><p>{{ __('marketing.pages.field_voice.panel_body') }}</p>@auth @if(auth()->user()->primaryOrganizationId())<a class="gs-button gs-button-accent" href="{{ route('organization.voice-assistance.index', auth()->user()->primaryOrganizationId()) }}">{{ __('marketing.pages.field_voice.panel_action') }}</a>@endif @else<a class="gs-button gs-button-accent" href="{{ route('login') }}">{{ __('marketing.pages.field_voice.panel_signin') }}</a>@endauth</aside></section>
    <section class="gs-boundaries"><div class="gs-container"><header><h2>{{ __('marketing.pages.field_voice.bounds_title') }}</h2></header><div><article><strong>{{ __('marketing.pages.field_voice.core_title') }}</strong><ul>@foreach(__('marketing.pages.field_voice.core_items') as $item)<li>{{ $item }}</li>@endforeach</ul></article><article><strong>{{ __('marketing.pages.field_voice.provider_title') }}</strong><ul>@foreach(__('marketing.pages.field_voice.provider_items') as $item)<li>{{ $item }}</li>@endforeach</ul></article></div></div></section>
</div>
@endsection
