<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#123B2A"><link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml"><link rel="apple-touch-icon" href="{{ asset('apple-touch-icon.png') }}"><title>@yield('title') · AgriShield</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="admin-page">
<aside class="admin-sidebar" data-sidebar><a class="brand brand-light" href="{{ route('home') }}"><img class="brand-symbol" src="{{ asset('brand/agrishield-mark.svg') }}" alt="" width="34" height="34"><span>Agri<strong>Shield</strong></span></a><div class="workspace-label"><span>{{ ($area ?? 'platform') === 'platform' ? 'Platform control' : 'Organization workspace' }}</span>@isset($organization)<strong>{{ $organization->name }}</strong>@else<strong>Operations desk</strong>@endisset</div><nav class="admin-nav" aria-label="Workspace navigation">
@if(($area ?? 'platform') === 'platform')<a href="{{ route('platform.dashboard') }}" @class(['active' => request()->routeIs('platform.dashboard')])><span>⌂</span>Overview</a><a href="{{ route('platform.organizations.index') }}" @class(['active' => request()->routeIs('platform.organizations.*')])><span>◇</span>Organizations</a><a href="{{ route('platform.users') }}" @class(['active' => request()->routeIs('platform.users')])><span>◎</span>People</a><a href="{{ route('platform.operations') }}" @class(['active' => request()->routeIs('platform.operations')])><span>↻</span>Operations</a>
@else<a href="{{ route('organization.dashboard', $organization) }}" @class(['active' => request()->routeIs('organization.dashboard')])><span>⌂</span>Overview</a><a href="{{ route('organization.farms.index', $organization) }}" @class(['active' => request()->routeIs('organization.farms.*')])><span>◇</span>Farms</a><a href="{{ route('organization.voice-assistance.index', $organization) }}" @class(['active' => request()->routeIs('organization.voice-assistance.*')])><span>◉</span>Field Voice</a><a href="{{ route('organization.advisories', $organization) }}" @class(['active' => request()->routeIs('organization.advisories')])><span>!</span>Advisories</a><a href="{{ route('organization.asset-finance.index', $organization) }}" @class(['active' => request()->routeIs('organization.asset-finance.*')])><span>▣</span>Asset Access</a>@can('viewMembers', $organization)<a href="{{ route('organization.team', $organization) }}" @class(['active' => request()->routeIs('organization.team')])><span>◎</span>Team</a>@endcan @endif
</nav><div class="sidebar-foot"><div class="user-avatar">{{ str(auth()->user()->name)->substr(0, 1)->upper() }}</div><div><strong>{{ auth()->user()->name }}</strong><span>{{ auth()->user()->email }}</span></div><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" aria-label="Sign out">↗</button></form></div></aside>
<div class="admin-shell"><header class="admin-topbar"><button class="admin-menu" type="button" data-admin-menu aria-label="Open navigation">☰</button><div><span>@yield('eyebrow', 'Agrishield')</span><strong>@yield('page-title')</strong></div><div class="topbar-meta"><span class="system-online"><i></i>System online</span><time>{{ now()->format('D, d M') }}</time></div></header><main class="admin-main">@yield('content')</main></div>
</body></html>
