@extends('layouts.admin', ['area' => 'platform'])
@section('title', 'Platform overview') @section('eyebrow', 'Platform control') @section('page-title', 'Operating picture')
@section('content')
<section class="page-lead"><div><p class="eyebrow"><span></span> {{ now()->format('l, d F') }}</p><h1>Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 17 ? 'afternoon' : 'evening') }}, {{ str(auth()->user()->name)->before(' ') }}.</h1><p>Here is the state of the Agrishield network right now.</p></div><a class="admin-button" href="{{ route('platform.organizations.index') }}">Review organizations <span>→</span></a></section>
<section class="metric-grid"><article><span>Active organizations</span><strong>{{ number_format($metrics['organizations']) }}</strong><small>Managed workspaces</small></article><article><span>Monitored farms</span><strong>{{ number_format($metrics['farms']) }}</strong><small>{{ number_format($metrics['hectares'], 1) }} hectares covered</small></article><article><span>People</span><strong>{{ number_format($metrics['users']) }}</strong><small>Across all roles</small></article><article class="metric-attention"><span>Needs attention</span><strong>{{ number_format($attention['criticalAdvisories'] + $attention['failedSyncs']) }}</strong><small>Critical advisories + failed syncs</small></article></section>
<div class="dashboard-grid"><section class="panel panel-wide"><div class="panel-head"><div><span>Portfolio</span><h2>Recently added organizations</h2></div><a href="{{ route('platform.organizations.index') }}">View all →</a></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Organization</th><th>Status</th><th>Farms</th><th>People</th><th>Added</th></tr></thead><tbody>@forelse($organizations as $item)<tr><td><a class="entity-link" href="{{ route('platform.organizations.show', $item) }}"><span class="entity-avatar">{{ str($item->name)->substr(0, 2)->upper() }}</span><strong>{{ $item->name }}</strong></a></td><td><span class="status-pill status-{{ $item->status->value }}">{{ str($item->status->value)->headline() }}</span></td><td>{{ $item->farms_count }}</td><td>{{ $item->users_count }}</td><td>{{ $item->created_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="5"><div class="empty-state"><strong>No organizations yet</strong><span>Organizations will appear here when they are created.</span></div></td></tr>@endforelse</tbody></table></div></section>
<aside class="panel attention-panel"><div class="panel-head"><div><span>Live attention</span><h2>Operations queue</h2></div></div><div class="attention-item"><i class="tone-red">{{ $attention['failedSyncs'] }}</i><div><strong>Failed syncs</strong><span>Require provider review</span></div></div><div class="attention-item"><i class="tone-orange">{{ $attention['unregisteredFarms'] }}</i><div><strong>Farm registrations</strong><span>Not yet registered</span></div></div><div class="attention-item"><i class="tone-green">{{ $syncRuns->where('status.value', 'succeeded')->count() }}</i><div><strong>Recent successes</strong><span>Across latest activity</span></div></div><a class="panel-action" href="{{ route('platform.operations') }}">Open operations desk <span>→</span></a></aside></div>
<section class="panel"><div class="panel-head"><div><span>Data pipeline</span><h2>Latest synchronization activity</h2></div></div><div class="activity-list">@forelse($syncRuns as $run)<div><span class="activity-icon status-{{ $run->status->value }}">{{ $run->status->value === 'succeeded' ? '✓' : '↻' }}</span><p><strong>{{ str($run->sync_type->value)->headline() }}</strong><span>{{ $run->farm?->name ?? 'Platform task' }} · {{ $run->provider }}</span></p><span class="status-pill status-{{ $run->status->value }}">{{ str($run->status->value)->headline() }}</span><time>{{ $run->created_at?->diffForHumans() }}</time></div>@empty<div class="empty-state"><strong>No synchronization activity</strong><span>Runs will appear when farms begin syncing.</span></div>@endforelse</div></section>
@endsection
